/**
 * In-process telemetry bus + state store for the Gene daemon.
 *
 * The daemon (src/index.ts, src/invoke.ts) publishes lifecycle events here as it
 * scans the tracker and dispatches agents; a view subscribes to the coalesced
 * `"change"` event and reads {@link Monitor.getState} to render. This is the
 * model/controller seam that lets the optional OpenTUI dashboard (src/ui/) observe
 * the daemon without the daemon ever importing OpenTUI — so the default console
 * mode keeps working on Node 24 and never touches native FFI.
 *
 * Like src/logger.ts and src/tracker, this is a process-wide singleton (`monitor`),
 * chosen at startup. Every publish method is best-effort and never throws:
 * telemetry must not be able to break the pipeline action it describes. When
 * nothing subscribes (console mode) the store still updates but emits nothing — a
 * quiet daemon pays almost nothing.
 *
 * NB: deliberately free of any @opentui/core import (and any heavy dependency) — it
 * holds only `node:events` — so importing it on any Node never pulls in FFI. The
 * one cross-module reference, {@link AgentEvent}, lives here (the model layer) so
 * both the producer (invoke.ts) and the view (src/ui/) share one shape.
 */

import { EventEmitter } from "node:events";

/**
 * One distilled agent stream event — the structured sibling of the one-line
 * summaries the daemon log prints. Produced by invoke.ts's `toAgentEvents` (the
 * single source of truth for which `claude -p` events matter), persisted to the
 * activity log's `data` column, and mirrored here so the dashboard's per-ticket
 * view can stream them live.
 */
export type AgentEvent =
  | { type: "session" }
  | { type: "text"; text: string }
  | { type: "tool_use"; tool: string; summary: string }
  | { type: "tool_error"; detail: string }
  | { type: "result"; subtype: string; durationMs?: number; result?: string };

/** Token accounting for one agent run, as reported by the `claude -p` stream. */
export interface TokenUsage {
  /** Input tokens (prompt + cache reads), summed across turns. */
  in: number;
  /** Output tokens generated by the agent, summed across turns. */
  out: number;
  /** Convenience sum (`in + out`). */
  total: number;
}

/**
 * Lifecycle of one dispatched agent run. Mirrors the outcomes invoke.ts can record
 * (agent-done / agent-error / agent-timeout / agent-cancelled) plus the two states
 * that exist only in memory before an outcome: "queued" (dispatched, not yet
 * spawned) and "running" (child alive). `interrupted` is reconstructed from the log
 * for a run whose daemon was killed mid-flight — `agent-start` was recorded but no
 * outcome ever followed (see src/db.ts findInterruptedRuns + the startup reconcile).
 */
export type AgentStatus = "queued" | "running" | "done" | "error" | "timeout" | "cancelled" | "blocked" | "interrupted";
export const AgentStatuses: AgentStatus[] = ["queued", "running", "done", "error", "timeout", "cancelled", "blocked", "interrupted"];

/**
 * Terminal STAGE shown once an issue reaches the tracker's Done state — it replaces
 * the (now stale) dispatch intent in the dashboard's STAGE column. Shared so the live
 * daemon (markIssueDone) and the history seed (ui/app.ts) agree on the literal.
 */
export const DONE_STAGE = "done";

/**
 * A status is terminal once the run has ended one way or another. `blocked` (moved
 * to the Blocked state — a clarification or a stall awaiting a human reply) counts:
 * the agent process is gone, even though a human can later re-dispatch it. So does
 * `interrupted`: the daemon (and its child) died, even though the next scan will
 * re-pick the still-active ticket up.
 */
export const isTerminalStatus = (status: AgentStatus): boolean =>
  status === "done" || status === "error" || status === "timeout" || status === "cancelled" ||
  status === "blocked" || status === "interrupted";

/** Live, in-memory view of one dispatched agent run, keyed by issue identifier. */
export interface AgentState {
  /** Human identifier, e.g. CLOUD-1094 (Issue.identifier). The map key. */
  id: string;
  /** Issue title, when known (set by the dashboard's history merge — not by the daemon). */
  title?: string;
  /** Workflow intent driving the run: start-processing / address-review / continue-draft / … */
  stage: string;
  /**
   * The issue's current tracker state (Todo / In Progress / Blocked / In Review / Done),
   * refreshed each scan by the daemon. Distinct from `stage` (the dispatch intent) and
   * `status` (the run outcome). Undefined until the first scan observes the issue.
   */
  lifecycleState?: string;
  /** Current lifecycle status. */
  status: AgentStatus;
  /** OS pid of the `claude -p` child, once spawned. */
  pid?: number;
  /** Epoch ms when the child spawned (drives the age column). */
  startedAt?: number;
  /** Epoch ms when the run reached a terminal status. */
  finishedAt?: number;
  /** One-line summary of the most recent event, for the table's EVENT column (plain text, no color). */
  lastEvent: string;
  /** Bounded ring of distilled events, newest appended, for the per-ticket detail view. */
  events: AgentEvent[];
  /** Count of tool_use events seen so far (the TOOLS column). */
  toolCount: number;
  /** Token usage, when the stream reports it (best-effort). */
  tokens?: TokenUsage;
  /** Wall-clock run duration in ms, set at finish. */
  durationMs?: number;
  /** Repo the agent works in, e.g. "group/app" — for the detail header. */
  repoLabel?: string;
  /** Work branch the agent's worktree is on, e.g. "fix/abc-123" — for the detail header. */
  branch?: string;
}

/** Summary counts from one scan cycle (mirrors the daemon's scan-summary log). */
export interface ScanSummary {
  /** Issues in the trigger state (Todo). */
  trigger: number;
  /** Issues in the active state (In Progress). */
  active: number;
  /** Issues in the blocked state. */
  blocked: number;
  /** Issues in the review state (In Review). */
  review: number;
  /** Issues in the done state — counted only when GENE_<TP>_DONE_STATE is configured. */
  done: number;
  /** Issues in any other (unwatched) state. */
  other: number;
  /** Total Gene issues assigned to the owner this scan. */
  total: number;
}

/** Process-level daemon state — the dashboard's top status block. */
export interface DaemonState {
  /** Epoch ms the daemon (and UI) started — drives uptime. */
  startedAt: number;
  /** Poll interval in ms (GENE_POLL_INTERVAL_MS) — the countdown's full width. */
  pollIntervalMs: number;
  /** Concurrency cap (GENE_MAX_CONCURRENT) — the "N/MAX" denominator. */
  maxConcurrent: number;
  /** True when GENE_DRY_RUN is on (shown as a [DRY-RUN] badge; no agents spawn). */
  dryRun: boolean;
  /** Active tracker name — "linear" / "trello" (tracker.name). */
  tracker: string;
  /** One-letter prefix shown on each ticket line — "L" / "T". Derived once at start. */
  trackerInitial: string;
  /** Gene label being watched (env.LABEL). */
  label: string;
  /** Whom Gene works for (env.ASSIGNEE: "me" / "any" / a specific user). */
  assignee: string;
  /** Configured terminal state name (env.DONE_STATE), when auto-Done is enabled — else undefined. */
  doneState?: string;
  /** Coarse current phase, for the header's "Stage:" line. */
  phase: "starting" | "scanning" | "idle";
  /** Epoch ms the last scan began. */
  lastScanAt?: number;
  /** Epoch ms the next scan is due — drives the "Next refresh" countdown. */
  nextScanAt?: number;
  /** Counts from the most recent completed scan. */
  lastScan?: ScanSummary;
  /** Most recent scan error message, if the last scan threw. */
  lastError?: string;
}

/** An immutable-by-convention snapshot the view reads on each `"change"`. */
export interface MonitorSnapshot {
  daemon: DaemonState;
  agents: AgentState[];
  /** Session-cumulative token totals, summed across every agent seen this run. */
  tokens: TokenUsage;
}

/** How many events to retain per agent for the detail view (oldest dropped past this). */
const EVENTS_RING_MAX = 1000;

/** Plain-text (no color) one-liner for the table's EVENT column, mirroring renderEvent's glyphs. */
const summarizeEvent = (event: AgentEvent): string => {
  switch (event.type) {
    case "session":
      return "▶ session started";
    case "text":
      return `→ ${event.text}`;
    case "tool_use":
      return `↳ ${event.summary}`;
    case "tool_error":
      return `⚠ ${event.detail}`;
    case "result": {
      const seconds = event.durationMs ? (event.durationMs / 1000).toFixed(1) : "?";
      return event.subtype === "success" ? `✓ done in ${seconds}s` : `✗ ${event.subtype} in ${seconds}s`;
    }
  }
};

/**
 * The telemetry singleton. Extends EventEmitter and emits a single coalesced
 * `"change"` event (one per microtask, only while something subscribes) whenever
 * the daemon or any agent state mutates.
 */
class Monitor extends EventEmitter {
  private daemon: DaemonState = {
    startedAt: Date.now(),
    pollIntervalMs: 60_000,
    maxConcurrent: 1,
    dryRun: true,
    tracker: "linear",
    trackerInitial: "L",
    label: "Gene",
    assignee: "me",
    phase: "starting"
  };

  /** Live + recently-finished agents, keyed by issue identifier (e.g. CLOUD-1094). */
  private agents = new Map<string, AgentState>();

  /**
   * Lifetime token total carried over from previous runs (sum of every persisted
   * run's usage, read from the DB at startup via {@link seedLifetimeTokens}). The
   * snapshot adds this base to the current session's agents, so the dashboard's
   * running total survives restarts. This session's agents are NOT in here — they
   * live in `agents` and are persisted on completion, so next startup folds them in.
   */
  private lifetimeBase: TokenUsage = { in: 0, out: 0, total: 0 };

  /** Kill closures registered by {@link agentSpawned}, used by {@link requestCancel}. */
  private cancels = new Map<string, () => void>();

  /** Identifiers the user asked to cancel — read by invoke.ts so a kill isn't auto-retried. */
  private cancelled = new Set<string>();

  /** Set while a `"change"` emit is already scheduled this microtask (coalescing). */
  private changeScheduled = false;

  /**
   * Emit a coalesced `"change"`. Multiple mutations in one synchronous burst
   * collapse to a single emit on the next microtask. No-op (and no scheduling)
   * when nothing subscribes, so console mode pays nothing.
   */
  private scheduleChange(): void {
    if (this.changeScheduled || this.listenerCount("change") === 0) {
      return;
    }
    this.changeScheduled = true;
    queueMicrotask(() => {
      this.changeScheduled = false;
      try {
        this.emit("change");
      } catch {
        // A misbehaving view listener must never crash the daemon.
      }
    });
  }

  /** Get-or-create the agent record for an identifier. */
  private upsert(id: string): AgentState {
    let agent = this.agents.get(id);
    if (!agent) {
      agent = { id, stage: "", status: "queued", lastEvent: "", events: [], toolCount: 0 };
      this.agents.set(id, agent);
    }
    return agent;
  }

  // --- Daemon lifecycle -----------------------------------------------------

  /** Record the daemon's static configuration and reset uptime. Derives trackerInitial. */
  daemonStarted(meta: {
    pollIntervalMs: number;
    maxConcurrent: number;
    dryRun: boolean;
    tracker: string;
    label: string;
    assignee: string;
    doneState?: string;
  }): void {
    this.daemon = {
      ...this.daemon,
      ...meta,
      startedAt: Date.now(),
      trackerInitial: (meta.tracker.charAt(0) || "?").toUpperCase(),
      phase: "starting"
    };
    this.scheduleChange();
  }

  /** Mark a scan cycle as begun. */
  scanStarted(): void {
    this.daemon.phase = "scanning";
    this.daemon.lastScanAt = Date.now();
    this.daemon.lastError = undefined;
    this.scheduleChange();
  }

  /** Record a finished scan's counts and when the next one is due. */
  scanFinished(summary: ScanSummary, nextScanAt: number): void {
    this.daemon.phase = "idle";
    this.daemon.lastScan = summary;
    this.daemon.nextScanAt = nextScanAt;
    this.scheduleChange();
  }

  /** Record that the last scan threw. */
  scanFailed(message: string): void {
    this.daemon.phase = "idle";
    this.daemon.lastError = message;
    this.scheduleChange();
  }

  // --- Agent lifecycle ------------------------------------------------------

  /**
   * A run has been dispatched (about to spawn). Creates/refreshes the agent in the
   * "queued" state and clears any stale cancellation flag from a prior run of the
   * same ticket, so a fresh dispatch is never pre-cancelled.
   */
  agentDispatched(id: string, stage: string, repoLabel: string, branch?: string, title?: string): void {
    this.cancelled.delete(id);
    const agent = this.upsert(id);
    agent.stage = stage;
    agent.repoLabel = repoLabel;
    agent.branch = branch;
    if (title) {
      agent.title = title;
    }
    agent.status = "queued";
    agent.startedAt = undefined;
    agent.finishedAt = undefined;
    agent.durationMs = undefined;
    agent.lastEvent = "queued…";
    agent.events = [];
    agent.toolCount = 0;
    agent.tokens = undefined;
    agent.pid = undefined;
    this.scheduleChange();
  }

  /**
   * Mark an issue's row as lifecycle-complete: replace the (now stale) dispatch stage
   * with {@link DONE_STAGE} once the issue reaches the tracker's Done state. Only
   * touches an existing row — a Done ticket that never ran this session gets no row —
   * and leaves the status glyph untouched (a Done ticket whose last run errored still
   * honestly reads `✗ done`). A later re-dispatch overwrites the stage via agentDispatched.
   */
  markIssueDone(id: string): void {
    const agent = this.agents.get(id);
    if (!agent || agent.stage === DONE_STAGE) {
      return;
    }
    agent.stage = DONE_STAGE;
    this.scheduleChange();
  }

  /**
   * Record the issue's current tracker state on its row (the STATE column), refreshed
   * each scan. Only touches an existing row — issues that never ran this session get no
   * row — so it's a no-op until a dispatched issue moves through the lifecycle.
   */
  setIssueState(id: string, state: string): void {
    const agent = this.agents.get(id);
    if (!agent || agent.lifecycleState === state) {
      return;
    }
    agent.lifecycleState = state;
    this.scheduleChange();
  }

  /** The `claude -p` child has spawned: record its pid and how to cancel it. */
  agentSpawned(id: string, pid: number, cancel: () => void): void {
    const agent = this.upsert(id);
    agent.pid = pid;
    agent.status = "running";
    agent.startedAt = Date.now();
    this.cancels.set(id, cancel);
    this.scheduleChange();
  }

  /** Append one distilled event, updating the one-liner + tool count. */
  agentEvent(id: string, event: AgentEvent): void {
    const agent = this.upsert(id);
    agent.events.push(event);
    if (agent.events.length > EVENTS_RING_MAX) {
      agent.events.splice(0, agent.events.length - EVENTS_RING_MAX);
    }
    if (event.type === "tool_use") {
      agent.toolCount += 1;
    }
    agent.lastEvent = summarizeEvent(event);
    this.scheduleChange();
  }

  /** Record token usage for a run (best-effort; the stream may not report it). */
  agentTokens(id: string, usage: TokenUsage): void {
    const agent = this.upsert(id);
    agent.tokens = usage;
    this.scheduleChange();
  }

  /** Record a run's terminal outcome. The entry stays in the map for the session. */
  agentFinished(id: string, status: AgentStatus, durationMs?: number): void {
    const agent = this.upsert(id);
    agent.status = status;
    agent.finishedAt = Date.now();
    if (durationMs !== undefined) {
      agent.durationMs = durationMs;
    }
    this.cancels.delete(id);
    this.scheduleChange();
  }

  /**
   * Finalize a still-pending entry that ended without a clean outcome (e.g. the
   * lock was held by another process, or the spawn threw before it ran). No-op if
   * the run already reported a terminal status.
   */
  agentSettled(id: string): void {
    const agent = this.agents.get(id);
    if (agent && !isTerminalStatus(agent.status)) {
      agent.status = "error";
      agent.finishedAt = Date.now();
      this.cancels.delete(id);
      this.scheduleChange();
    }
  }

  // --- View API -------------------------------------------------------------

  /**
   * Seed the lifetime token base from persisted history (DB sum), once at startup
   * before any run this session completes — so the base and the session's agents
   * stay disjoint and the running total never double-counts.
   */
  seedLifetimeTokens(base: { in: number; out: number }): void {
    this.lifetimeBase = { in: base.in, out: base.out, total: base.in + base.out };
    this.scheduleChange();
  }

  /** Snapshot for the view: daemon state, all agents, and cumulative token totals. */
  getState(): MonitorSnapshot {
    const tokens: TokenUsage = { ...this.lifetimeBase };
    for (const agent of this.agents.values()) {
      if (agent.tokens) {
        tokens.in += agent.tokens.in;
        tokens.out += agent.tokens.out;
        tokens.total += agent.tokens.total;
      }
    }
    return { daemon: this.daemon, agents: [...this.agents.values()], tokens };
  }

  /** Read one agent by identifier (the detail view's live source). */
  getAgent(id: string): AgentState | undefined {
    return this.agents.get(id);
  }

  /**
   * Request cancellation of a run: flag it (so invoke.ts treats the kill as
   * non-retriable) and, if it has spawned, invoke its kill closure. Returns true
   * when a live child was signalled.
   */
  requestCancel(id: string): boolean {
    this.cancelled.add(id);
    const cancel = this.cancels.get(id);
    if (!cancel) {
      return false;
    }
    try {
      cancel();
    } catch {
      // already exited — nothing to signal
    }
    return true;
  }

  /** Whether the user asked to cancel this run (read by invoke.ts's retry loop). */
  isCancelled(id: string): boolean {
    return this.cancelled.has(id);
  }
}

/** The process-wide telemetry singleton. */
export const monitor = new Monitor();

export default monitor;
